"""init identity and organization tables

Revision ID: dcc811e0f1a6
Revises: 
Create Date: 2026-08-04 18:03:09.959924+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc811e0f1a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到当前版本"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parents'))
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_phone'), ['phone'], unique=True)

    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False, comment='学校名称'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='所在地区'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='详细地址'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('current_semester', sa.String(length=50), nullable=True, comment='当前学期，如 2025-秋'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('grades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='年级名称，如 高一'),
    sa.Column('school_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='所属学校'),
    sa.Column('academic_year', sa.String(length=20), nullable=True, comment='所属学年，如 2024-2025'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_grades_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades'))
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_school_id'), ['school_id'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.Enum('admin', 'academic_admin', 'subject_lead', 'teacher', name='teacherrole', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_teachers_school_id_schools'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers'))
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_school_id'), ['school_id'], unique=False)

    op.create_table('classes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='班级名称'),
    sa.Column('grade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='所属年级'),
    sa.Column('homeroom_teacher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='班主任 Teacher.id'),
    sa.Column('student_count', sa.Integer(), nullable=False, comment='当前学生人数（冗余，服务层维护）'),
    sa.Column('stage', sa.Enum('junior', 'senior', name='schoolstage', native_enum=False, create_constraint=True, length=20), nullable=True, comment='学段 junior/senior'),
    sa.Column('subject', sa.String(length=20), nullable=False, comment='学科，固定 chemistry'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_classes_grade_id_grades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['teachers.id'], name=op.f('fk_classes_homeroom_teacher_id_teachers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_homeroom_teacher_id'), ['homeroom_teacher_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('student_number', sa.String(length=32), nullable=True),
    sa.Column('class_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('bind_code', sa.String(length=6), nullable=True),
    sa.Column('barrier_profile', sa.JSON(), nullable=True),
    sa.Column('barrier_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_practice_count', sa.Integer(), nullable=False),
    sa.Column('last_practice_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_students_class_id_classes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_bind_code'), ['bind_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_number'), ['student_number'], unique=True)

    op.create_table('teacher_class_subjects',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('class_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科（默认化学）'),
    sa.Column('is_head_teacher', sa.Boolean(), nullable=False, comment='是否为该班班主任'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_teacher_class_subjects_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_class_subjects_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_class_subjects')),
    sa.UniqueConstraint('teacher_id', 'class_id', 'subject', name=op.f('uq_teacher_class_subjects_teacher_id_class_id_subject'))
    )
    with op.batch_alter_table('teacher_class_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_class_subjects_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_class_subjects_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间（NULL 表示未删除）'),
    sa.CheckConstraint("role IN ('admin', 'academic_admin', 'subject_lead', 'teacher', 'student')", name=op.f('ck_accounts_role_allowed')),
    sa.CheckConstraint('(teacher_id IS NULL) != (student_id IS NULL)', name=op.f('ck_accounts_teacher_xor_student')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_accounts_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_accounts_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_teacher_id'), ['teacher_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('student_parent_bindings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('relationship_type', sa.Enum('father', 'mother', 'guardian', name='parentrelation', native_enum=False, create_constraint=True, length=20), nullable=False, comment='关系：father/mother/guardian'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='绑定是否有效'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name=op.f('fk_student_parent_bindings_parent_id_parents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_parent_bindings_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_parent_bindings')),
    sa.UniqueConstraint('student_id', 'parent_id', name='uq_binding_student_parent')
    )
    with op.batch_alter_table('student_parent_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_parent_bindings_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_parent_bindings_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """降级到上一版本"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_parent_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_parent_bindings_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_parent_bindings_parent_id'))

    op.drop_table('student_parent_bindings')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_accounts_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_student_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('teacher_class_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_class_subjects_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_class_subjects_class_id'))

    op.drop_table('teacher_class_subjects')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_number'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))
        batch_op.drop_index(batch_op.f('ix_students_bind_code'))

    op.drop_table('students')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_homeroom_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classes_grade_id'))

    op.drop_table('classes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_school_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_phone'))

    op.drop_table('teachers')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_school_id'))

    op.drop_table('grades')
    op.drop_table('schools')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_phone'))

    op.drop_table('parents')
    # ### end Alembic commands ###
